CREATE TABLE "url_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "url_table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"code" varchar(255),
	"targetUrl" varchar(255) NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"clickCount" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "url_table_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "url_table" ADD CONSTRAINT "url_table_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "url_code_unique_indx" ON "url_table" USING btree ("code");--> statement-breakpoint
CREATE INDEX "expiresAt_index" ON "url_table" USING btree ("expiresAt");